package com.example.ds_project.controllers;

import com.example.ds_project.models.ToyIdentificationDetails;
import com.example.ds_project.models.ToyInformation;
import com.example.ds_project.models.ToyManufacturerDetails;
import com.example.ds_project.repository.ToyIdentificationDetailsRepository;
import com.example.ds_project.repository.ToyInformationRepository;
import com.example.ds_project.repository.ToyManufacturerInformationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ToyIdentificationDetailsRepository identificationDetailsRepository;
    private ToyManufacturerInformationRepository manufacturerInformationRepository;
    private ToyInformationRepository informationRepository;

    @PostMapping(path="/id") // Map ONLY POST Requests
    public @ResponseBody String addNewId (@RequestParam String name
            , @RequestParam Integer code) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        ToyIdentificationDetails n = new ToyIdentificationDetails();
        n.setToy_name(name);
        n.setToy_code(code);
        identificationDetailsRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/ids")
    public @ResponseBody Iterable<ToyIdentificationDetails> getAllIds() {
        // This returns a JSON or XML with the users
        System.out.println("Found");
        return identificationDetailsRepository.findAll();
    }

    @PostMapping(path="/manufacturer") // Map ONLY POST Requests
    public @ResponseBody String addNewManufacturer (@RequestParam String companyName, @RequestParam String streetAddress, @RequestParam String country
            , @RequestParam Integer zipCode) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        ToyManufacturerDetails n = new ToyManufacturerDetails();
        n.setCompanyName(companyName);
        n.setCountry(country);
        n.setStreetAddress(streetAddress);
        n.setZipCode(zipCode);
        manufacturerInformationRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/manufacturers")
    public @ResponseBody Iterable<ToyManufacturerDetails> getAllManufacturers() {
        // This returns a JSON or XML with the users
        System.out.println("Found");
        return manufacturerInformationRepository.findAll();
    }

    @PostMapping(path="/toy") // Map ONLY POST Requests
    public @ResponseBody String addNewToy (@RequestParam String companyName, @RequestParam String toyName, @RequestParam String description
            , @RequestParam Integer price, @RequestParam Integer date, @RequestParam Integer batchNo) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        ToyInformation n = new ToyInformation();
        n.setName(toyName);
        n.setDescription(description);
        n.setPrice(price);
        n.setDateOfManufacture(date);
        n.setBatchNumber(batchNo);
        informationRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/toys")
    public @ResponseBody Iterable<ToyInformation> getAllToys() {
        // This returns a JSON or XML with the users
        System.out.println("Found");
        return informationRepository.findAll();
    }

}